"""Extended format registry entries — audio, image, video, code, adversarial.

Formats that require optional dependencies or cover additional languages
and advanced embedding techniques. Merged into FORMAT_REGISTRY by the
main registry module.
"""

from pistudio.files.formats.types import FileFormat
from pistudio.files.formats.writers_ext import (
    _write_adversarial_audio_stub,
    _write_anamorph_stub,
    _write_audio_stego_stub,
    _write_spectro_text_stub,
    _write_tts_concat_stub,
    _write_tts_wav_stub,
    _write_tts_whisper_stub,
    _write_ultrasonic_stub,
    write_bat,
    write_bib,
    write_bmp,
    write_c,
    write_cert,
    write_flac,
    write_gif,
    write_go,
    write_ipynb,
    write_java,
    write_midi,
    write_mp3,
    write_mp4,
    write_obj,
    write_ogg,
    write_ps1,
    write_rb,
    write_rs,
    write_stl,
    write_ts,
    write_ttf,
    write_webp,
)

EXT_FORMATS: dict[str, FileFormat] = {
    # -- Tier A: Audio (optional dep) --
    "mp3": FileFormat(
        "mp3",
        ".mp3",
        "MP3 audio (ID3 tags)",
        "mutagen",
        write_mp3,
        False,
        False,
        group="embed-audio",
        category="Audio",
        threat_level="documented",
        audio=True,
    ),
    # -- Tier A: Vision / multimodal (Pillow from [embed]) --
    "webp": FileFormat(
        "webp",
        ".webp",
        "WebP image (rendered text)",
        "Pillow",
        write_webp,
        False,
        False,
        group="embed",
        category="Images",
        threat_level="documented",
    ),
    "gif": FileFormat(
        "gif",
        ".gif",
        "GIF image (rendered text)",
        "Pillow",
        write_gif,
        False,
        False,
        group="embed",
        category="Images",
        threat_level="documented",
    ),
    "bmp": FileFormat(
        "bmp",
        ".bmp",
        "BMP image (rendered text)",
        "Pillow",
        write_bmp,
        False,
        False,
        group="embed",
        category="Images",
        threat_level="documented",
    ),
    # -- Tier A: Jupyter notebooks (optional dep) --
    "ipynb": FileFormat(
        "ipynb",
        ".ipynb",
        "Jupyter notebook (markdown cell)",
        "nbformat",
        write_ipynb,
        False,
        False,
        group="embed-notebook",
        category="Notebooks",
        threat_level="documented",
    ),
    # -- Tier B: Additional code languages (stdlib) --
    "ts": FileFormat(
        "ts",
        ".ts",
        "TypeScript file (block comment)",
        "",
        write_ts,
        True,
        False,
        category="Code",
        threat_level="exploratory",
    ),
    "java": FileFormat(
        "java",
        ".java",
        "Java file (Javadoc comment)",
        "",
        write_java,
        True,
        False,
        category="Code",
        threat_level="exploratory",
    ),
    "go": FileFormat(
        "go", ".go", "Go file (line comments)", "", write_go, True, False, category="Code", threat_level="exploratory"
    ),
    "rb": FileFormat(
        "rb", ".rb", "Ruby file (comments)", "", write_rb, True, False, category="Code", threat_level="exploratory"
    ),
    "rs": FileFormat(
        "rs", ".rs", "Rust file (line comments)", "", write_rs, True, False, category="Code", threat_level="exploratory"
    ),
    "c": FileFormat(
        "c", ".c", "C file (block comment)", "", write_c, True, False, category="Code", threat_level="exploratory"
    ),
    # -- Tier B: Additional scripting / config (stdlib) --
    "bat": FileFormat(
        "bat",
        ".bat",
        "Windows batch file (REM comments)",
        "",
        write_bat,
        True,
        False,
        category="Code",
        threat_level="exploratory",
    ),
    "ps1": FileFormat(
        "ps1",
        ".ps1",
        "PowerShell script (comments)",
        "",
        write_ps1,
        True,
        False,
        category="Code",
        threat_level="exploratory",
    ),
    # -- Tier B: Academic (stdlib) --
    "bib": FileFormat(
        "bib",
        ".bib",
        "BibTeX entry (abstract field)",
        "",
        write_bib,
        True,
        False,
        category="Documents",
        threat_level="exploratory",
    ),
    # -- Tier B: Audio (optional deps) --
    "flac": FileFormat(
        "flac",
        ".flac",
        "FLAC audio (Vorbis comment)",
        "mutagen",
        write_flac,
        False,
        False,
        group="embed-audio",
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    "ogg": FileFormat(
        "ogg",
        ".ogg",
        "OGG audio (Vorbis comment)",
        "mutagen",
        write_ogg,
        False,
        False,
        group="embed-audio",
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    "midi": FileFormat(
        "midi",
        ".mid",
        "MIDI file (text event)",
        "mido",
        write_midi,
        False,
        False,
        group="embed-audio",
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    # -- Tier B: OBJ 3D model (stdlib) --
    "obj": FileFormat(
        "obj",
        ".obj",
        "Wavefront OBJ (comment)",
        "",
        write_obj,
        True,
        False,
        category="3D & Misc",
        threat_level="exploratory",
    ),
    # -- Tier B: Video (optional dep) --
    "mp4": FileFormat(
        "mp4",
        ".mp4",
        "MP4 video (subtitle track)",
        "moviepy",
        write_mp4,
        False,
        False,
        group="embed-video",
        category="Video",
        threat_level="exploratory",
    ),
    # -- Tier B: Font (optional dep) --
    "ttf": FileFormat(
        "ttf",
        ".ttf",
        "TrueType font (name table)",
        "fonttools",
        write_ttf,
        False,
        False,
        group="embed-extra",
        category="3D & Misc",
        threat_level="exploratory",
    ),
    # -- Tier B: STL 3D model (optional dep) --
    "stl": FileFormat(
        "stl",
        ".stl",
        "STL 3D model (header)",
        "numpy",
        write_stl,
        False,
        False,
        group="embed-extra",
        category="3D & Misc",
        threat_level="exploratory",
    ),
    # -- Adversarial (optional dep) --
    "anamorph": FileFormat(
        "anamorph",
        ".png",
        "Adversarial image (scaling attack)",
        "anamorpher",
        _write_anamorph_stub,
        False,
        False,
        group="embed-anamorpher",
        category="Adversarial",
        threat_level="documented",
    ),
    # -- Protocol metadata (offline; nothing is transmitted) --
    "cert": FileFormat(
        "cert",
        ".pem",
        "X.509 certificate (payload in Subject Alternative Name)",
        "",
        write_cert,
        False,
        False,
        category="Protocol",
        threat_level="documented",
    ),
    # -- Audio Prompt Injection (TTS) --
    "tts-wav": FileFormat(
        "tts-wav",
        ".wav",
        "TTS speech synthesis (prompt as audio)",
        "edge-tts",
        _write_tts_wav_stub,
        False,
        False,
        group="embed-audio-tts",
        category="Audio",
        threat_level="documented",
        audio=True,
    ),
    "tts-whisper": FileFormat(
        "tts-whisper",
        ".wav",
        "Low-volume TTS (whisper under carrier)",
        "edge-tts",
        _write_tts_whisper_stub,
        False,
        False,
        group="embed-audio-tts",
        category="Audio",
        threat_level="documented",
        audio=True,
    ),
    "tts-concat": FileFormat(
        "tts-concat",
        ".wav",
        "Multi-voice TTS concatenation",
        "edge-tts",
        _write_tts_concat_stub,
        False,
        False,
        group="embed-audio-tts",
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    # -- Audio Prompt Injection (Advanced) --
    "ultrasonic": FileFormat(
        "ultrasonic",
        ".wav",
        "Near-ultrasonic FSK encoding (16-20kHz)",
        "numpy",
        _write_ultrasonic_stub,
        False,
        False,
        group="embed-audio-adv",
        category="Audio",
        threat_level="documented",
        audio=True,
    ),
    "audio-stego": FileFormat(
        "audio-stego",
        ".wav",
        "LSB steganography in WAV samples",
        "",
        _write_audio_stego_stub,
        False,
        False,
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    "spectro-text": FileFormat(
        "spectro-text",
        ".wav",
        "Spectrogram watermark (text in freq domain)",
        "numpy",
        _write_spectro_text_stub,
        False,
        False,
        group="embed-audio-adv",
        category="Audio",
        threat_level="exploratory",
        audio=True,
    ),
    # -- Adversarial Audio (venv-isolated) --
    "adversarial-audio": FileFormat(
        "adversarial-audio",
        ".wav",
        "Adversarial perturbation (white-box ASR attack)",
        "adversarial-audio",
        _write_adversarial_audio_stub,
        False,
        False,
        group="embed-adversarial-audio",
        category="Adversarial",
        threat_level="documented",
        audio=True,
    ),
}
